# Generated by Django 4.2.5 on 2023-09-27 17:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("authsystem", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
